[agent]
  interval = "10s"
  flush_interval = "10s"

[[inputs.mqtt_consumer]]
  servers = ["tcp://localhost:1883"]
  topics = ["tanque/datos"]
  data_format = "json_v2"

  [[inputs.mqtt_consumer.json_v2]]
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "nivel_m"
      type = "float"
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "masa_kg"
      type = "float"
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "ciclo"
      type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "temp.0"
      rename = "temp_DS0"
      type = "float"
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "temp.1"
      rename = "temp_DS1"
      type = "float"
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "temp.2"
      rename = "temp_DS2"
      type = "float"
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "temp.3"
      rename = "temp_DS3"
      type = "float"
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "temp.4"
      rename = "temp_DS4"
      type = "float"
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "t_amb"
      type = "float"
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "t_sup"
      type = "float"
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "flujo_entrada_lmin"
      type = "float"
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "flujo_salida_lmin"
      type = "float"
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "vol_entrada_l"
      type = "float"
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "vol_salida_l"
      type = "float"
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "bomba"
      type = "bool"

[[inputs.cpu]]
  percpu = false
  totalcpu = true
  collect_cpu_time = false
  report_active = false

[[inputs.mem]]

[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs"]

[[inputs.temp]]

[[outputs.influxdb_v2]]
  urls = ["http://localhost:8086"]
  token = "3MycBr7zwAzy_L-xUsiarFMKELOqhrGqqcwJf_14YF4NmTSNePnOw5uMcwCXZQwmp3DS1JmhHeN-cEIa9TldNw=="
  organization = "uach"
  bucket = "gemelo_telegraf"
